Control de Flujo

In [0]:
a=20
b=30

if a>b:
  print("a>b")
elif a<b:
  print("a<b")
else:
  print("a=b")

a<b


In [0]:
a=20
b=30

print("a>b") if a>b else print("es diferente")

es diferente


In [0]:
i=1
while i<6:
  i+=1
  print(i)
  if i==4: break


2
3
4


In [0]:
f=['a','b','c']
for x in f:
  print(x)

a
b
c


In [0]:
for x in range(6):
  print(x)

0
1
2
3
4
5


In [0]:
for x in range(2,6):
  print(x)

2
3
4
5


In [0]:
for x in range(2,60,3):
  print(x)

2
5
8
11
14
17
20
23
26
29
32
35
38
41
44
47
50
53
56
59


In [0]:
x = lambda a:a+10
print(x(5))


#def x(n):
#  return(n+10)

15


In [0]:
x = lambda a,b:a*b
print(x(3,4))

x= lambda a,b,c: a+b+c
print(x(1,2,3))

12
6


In [0]:
def myfunc(n):
  return lambda a:a*n 

mydouble=myfunc(2)
mytriple=myfunc(3)

print(mydouble(3))
print(mytriple(4))


6
12


**Numpy**

In [0]:
import numpy as np

data=np.random.randn(2,3)
print(data)
print(data*10)
print(data+data)

[[-1.09977567 -2.57068608  1.62714333]
 [-0.51166188  0.43870462  1.06800458]]
[[-10.99775671 -25.70686076  16.27143332]
 [ -5.11661883   4.38704622  10.68004578]]
[[-2.19955134 -5.14137215  3.25428666]
 [-1.02332377  0.87740924  2.13600916]]


In [0]:
data.shape

(2, 3)

In [0]:
data.dtype

dtype('float64')

In [0]:
data1=[6,7,8,9,0,2]

arr1=np.array(data1)

print(arr1)

[6 7 8 9 0 2]


In [0]:
data2=[[1,2,3,4,5],[6,7,8,9,0]]
arr2=np.array(data2)
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [0]:
arr1.shape

(6,)

In [0]:
arr2.shape

(2, 5)

In [0]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5]

5

In [0]:
arr[5:8]

array([5, 6, 7])

In [0]:
arr[0:3]=0
arr

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[:4]

array([0, 0, 0, 3])

In [0]:
arr[2:]

array([0, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[:]

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr2d=np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [0]:
arr2d[1]

array([6, 7, 8, 9, 0])

In [0]:
arr2d[0][2]

3

In [0]:
arr2d[0,2]

3

In [0]:
arr2d[:1,1:]

array([[2, 3, 4, 5]])

In [0]:
arr2d[:,:4]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [0]:
names=np.array(['Juan', 'Jose', 'Carlos', 'Manuel', 'Maria', 'Andrea', 'Juana'])

In [0]:
names

array(['Juan', 'Jose', 'Carlos', 'Manuel', 'Maria', 'Andrea', 'Juana'],
      dtype='<U6')

In [0]:
data=np.random.rand(7,4)
data

array([[0.25447005, 0.73454463, 0.55241375, 0.30884296],
       [0.54326692, 0.55944243, 0.94917923, 0.15968057],
       [0.68714974, 0.88838449, 0.22715255, 0.58803347],
       [0.3266428 , 0.87670611, 0.41207588, 0.987085  ],
       [0.08218788, 0.15694985, 0.62049799, 0.79876237],
       [0.75026182, 0.267113  , 0.94434183, 0.68100552],
       [0.1164529 , 0.53177003, 0.94380642, 0.36903003]])

In [0]:
names=='Juan'

array([ True, False, False, False, False, False, False])

In [0]:
names=='Maria'

array([False, False, False, False,  True, False, False])

In [0]:
data[names=='Juan']

array([[0.25447005, 0.73454463, 0.55241375, 0.30884296]])

In [0]:
data[names=='Juan',2:]

array([[0.55241375, 0.30884296]])

In [0]:
# and es &
# or es |
# not es ~

data[(names=='Juan') | (names=='Maria'),]

array([[0.25447005, 0.73454463, 0.55241375, 0.30884296],
       [0.08218788, 0.15694985, 0.62049799, 0.79876237]])

In [0]:
data[~(names=='Juan')]

array([[0.54326692, 0.55944243, 0.94917923, 0.15968057],
       [0.68714974, 0.88838449, 0.22715255, 0.58803347],
       [0.3266428 , 0.87670611, 0.41207588, 0.987085  ],
       [0.08218788, 0.15694985, 0.62049799, 0.79876237],
       [0.75026182, 0.267113  , 0.94434183, 0.68100552],
       [0.1164529 , 0.53177003, 0.94380642, 0.36903003]])

In [0]:
data[(names!='Juan')]

array([[0.54326692, 0.55944243, 0.94917923, 0.15968057],
       [0.68714974, 0.88838449, 0.22715255, 0.58803347],
       [0.3266428 , 0.87670611, 0.41207588, 0.987085  ],
       [0.08218788, 0.15694985, 0.62049799, 0.79876237],
       [0.75026182, 0.267113  , 0.94434183, 0.68100552],
       [0.1164529 , 0.53177003, 0.94380642, 0.36903003]])

In [0]:
data>0.4

array([[False,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True, False]])

In [0]:
data[data>0.4]

array([0.73454463, 0.55241375, 0.54326692, 0.55944243, 0.94917923,
       0.68714974, 0.88838449, 0.58803347, 0.87670611, 0.41207588,
       0.987085  , 0.62049799, 0.79876237, 0.75026182, 0.94434183,
       0.68100552, 0.53177003, 0.94380642])

Estadistica Numpy

In [0]:
data.mean()

0.5470446502741246

In [0]:
np.mean(data)

0.5470446502741246

In [0]:
data.sum()

15.31725020767549

In [0]:
np.sum(data)

15.31725020767549

In [0]:
a=data.std()
b=data.var()
c=data.min()
d=data.max()

print(a,b,c,d)


0.28068407388080513 0.07878354933032526 0.08218788325576076 0.9870850011861764


In [0]:
d=[1,2,3,4,5,6]
darr=np.array(d)
print(darr)
print(darr.cumsum())
print(darr.cumprod())



[1 2 3 4 5 6]
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]


In [0]:
print(data)

[[0.25447005 0.73454463 0.55241375 0.30884296]
 [0.54326692 0.55944243 0.94917923 0.15968057]
 [0.68714974 0.88838449 0.22715255 0.58803347]
 [0.3266428  0.87670611 0.41207588 0.987085  ]
 [0.08218788 0.15694985 0.62049799 0.79876237]
 [0.75026182 0.267113   0.94434183 0.68100552]
 [0.1164529  0.53177003 0.94380642 0.36903003]]


In [0]:



print(data.cumsum(axis=0))

[[0.25447005 0.73454463 0.55241375 0.30884296]
 [0.79773696 1.29398706 1.50159298 0.46852353]
 [1.4848867  2.18237155 1.72874554 1.056557  ]
 [1.8115295  3.05907766 2.14082142 2.043642  ]
 [1.89371738 3.21602751 2.7613194  2.84240437]
 [2.6439792  3.4831405  3.70566123 3.52340989]
 [2.7604321  4.01491054 4.64946765 3.89243992]]


In [0]:
print(data.cumsum(axis=1))

[[0.25447005 0.98901468 1.54142843 1.85027139]
 [0.54326692 1.10270935 2.05188858 2.21156914]
 [0.68714974 1.57553422 1.80268678 2.39072025]
 [0.3266428  1.20334891 1.61542478 2.60250978]
 [0.08218788 0.23913773 0.85963572 1.65839809]
 [0.75026182 1.01737482 1.96171665 2.64272217]
 [0.1164529  0.64822293 1.59202935 1.96105938]]


**Pandas**

In [0]:
import pandas as pd

In [0]:
data={'state':['OH','OH','OH','NE','NE','NE'],
      'year':[2000,2001,2002,2000,2001,2002],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

print(data)

{'state': ['OH', 'OH', 'OH', 'NE', 'NE', 'NE'], 'year': [2000, 2001, 2002, 2000, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}


In [0]:
frame=pd.DataFrame(data)

print(frame)

  state  year  pop
0    OH  2000  1.5
1    OH  2001  1.7
2    OH  2002  3.6
3    NE  2000  2.4
4    NE  2001  2.9
5    NE  2002  3.2


In [0]:
frame.head()

state  year  pop
0    OH  2000  1.5
1    OH  2001  1.7
2    OH  2002  3.6
3    NE  2000  2.4
4    NE  2001  2.9

In [0]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   state   6 non-null      object 
 1   year    6 non-null      int64  
 2   pop     6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 272.0+ bytes


In [0]:
frame.shape

(6, 3)

In [0]:
frame.describe()

year       pop
count     6.000000  6.000000
mean   2001.000000  2.550000
std       0.894427  0.836062
min    2000.000000  1.500000
25%    2000.250000  1.875000
50%    2001.000000  2.650000
75%    2001.750000  3.125000
max    2002.000000  3.600000

In [0]:
frame.year

0    2000
1    2001
2    2002
3    2000
4    2001
5    2002
Name: year, dtype: int64

In [0]:
frame.state

0    OH
1    OH
2    OH
3    NE
4    NE
5    NE
Name: state, dtype: object

In [0]:
frame['year']

0    2000
1    2001
2    2002
3    2000
4    2001
5    2002
Name: year, dtype: int64

In [0]:
frame['state']

0    OH
1    OH
2    OH
3    NE
4    NE
5    NE
Name: state, dtype: object

In [0]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [0]:
frame.values

array([['OH', 2000, 1.5],
       ['OH', 2001, 1.7],
       ['OH', 2002, 3.6],
       ['NE', 2000, 2.4],
       ['NE', 2001, 2.9],
       ['NE', 2002, 3.2]], dtype=object)

In [0]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [0]:
frame.sum()

state    OHOHOHNENENE
year            12006
pop              15.3
dtype: object

In [0]:
frame.mean()

year    2001.00
pop        2.55
dtype: float64

In [0]:
frame.min()

state      NE
year     2000
pop       1.5
dtype: object

In [0]:
frame.cumsum()

state   year   pop
0            OH   2000   1.5
1          OHOH   4001   3.2
2        OHOHOH   6003   6.8
3      OHOHOHNE   8003   9.2
4    OHOHOHNENE  10004  12.1
5  OHOHOHNENENE  12006  15.3

In [0]:
frame.cummax()

state  year  pop
0    OH  2000  1.5
1    OH  2001  1.7
2    OH  2002  3.6
3    OH  2002  3.6
4    OH  2002  3.6
5    OH  2002  3.6